//
//  SRSongs.swift
//  MyNoteTrainer
//
//  Created by Widya Limarto on 23/08/22.
//

import Foundation

struct SRSongs {
    static let test: [Note] = [
        Note(noteType: .fullNote, sound: Sound(tone: .F)),
        Note(noteType: .halfNote, sound: Sound(tone: .F)),
        Note(noteType: .eighthNote, sound: Sound(tone: .F)),
        Note(noteType: .fullRest, sound: Sound(tone: .F)),
        Note(noteType: .halfRest, sound: Sound(tone: .F)),
        Note(noteType: .eighthRest, sound: Sound(tone: .F))
    ]
    
    static let twinkle: [Note] = [
        Note(noteType: .quarterNote, sound: Sound(tone: .C)),
        Note(noteType: .quarterNote, sound: Sound(tone: .C)),
        Note(noteType: .quarterNote, sound: Sound(tone: .G)),
        Note(noteType: .quarterNote, sound: Sound(tone: .G)),
        Note(noteType: .quarterNote, sound: Sound(tone: .A)),
        Note(noteType: .quarterNote, sound: Sound(tone: .A)),
        Note(noteType: .quarterNote, sound: Sound(tone: .G)),
        Note(noteType: .quarterRest, sound: Sound(tone: .F)),
        Note(noteType: .quarterNote, sound: Sound(tone: .F)),
        Note(noteType: .quarterNote, sound: Sound(tone: .F)),
        Note(noteType: .quarterNote, sound: Sound(tone: .E)),
        Note(noteType: .quarterNote, sound: Sound(tone: .E)),
        Note(noteType: .quarterNote, sound: Sound(tone: .D)),
        Note(noteType: .quarterNote, sound: Sound(tone: .D)),
        Note(noteType: .quarterNote, sound: Sound(tone: .C)),
        Note(noteType: .quarterRest, sound: Sound(tone: .F)),
        Note(noteType: .quarterNote, sound: Sound(tone: .G)),
        Note(noteType: .quarterNote, sound: Sound(tone: .G)),
        Note(noteType: .quarterNote, sound: Sound(tone: .F)),
        Note(noteType: .quarterNote, sound: Sound(tone: .F)),
        Note(noteType: .quarterNote, sound: Sound(tone: .E)),
        Note(noteType: .quarterNote, sound: Sound(tone: .E)),
        Note(noteType: .quarterNote, sound: Sound(tone: .D)),
        Note(noteType: .quarterRest, sound: Sound(tone: .F)),
        Note(noteType: .quarterNote, sound: Sound(tone: .G)),
        Note(noteType: .quarterNote, sound: Sound(tone: .G)),
        Note(noteType: .quarterNote, sound: Sound(tone: .F)),
        Note(noteType: .quarterNote, sound: Sound(tone: .F)),
        Note(noteType: .quarterNote, sound: Sound(tone: .E)),
        Note(noteType: .quarterNote, sound: Sound(tone: .E)),
        Note(noteType: .quarterNote, sound: Sound(tone: .D)),
        Note(noteType: .quarterRest, sound: Sound(tone: .F)),
        Note(noteType: .quarterNote, sound: Sound(tone: .C)),
        Note(noteType: .quarterNote, sound: Sound(tone: .C)),
        Note(noteType: .quarterNote, sound: Sound(tone: .G)),
        Note(noteType: .quarterNote, sound: Sound(tone: .G)),
        Note(noteType: .quarterNote, sound: Sound(tone: .A)),
        Note(noteType: .quarterNote, sound: Sound(tone: .A)),
        Note(noteType: .quarterNote, sound: Sound(tone: .G)),
        Note(noteType: .quarterRest, sound: Sound(tone: .F)),
        Note(noteType: .quarterNote, sound: Sound(tone: .F)),
        Note(noteType: .quarterNote, sound: Sound(tone: .F)),
        Note(noteType: .quarterNote, sound: Sound(tone: .E)),
        Note(noteType: .quarterNote, sound: Sound(tone: .E)),
        Note(noteType: .quarterNote, sound: Sound(tone: .D)),
        Note(noteType: .quarterNote, sound: Sound(tone: .D)),
        Note(noteType: .quarterNote, sound: Sound(tone: .C)),
        Note(noteType: .quarterRest, sound: Sound(tone: .F))
    ]
    
    static let jaychou: [Note] = [
        Note(noteType: .quarterNote, sound: Sound(tone: .F)),
        Note(noteType: .quarterNote, sound: Sound(tone: .G)),
        Note(noteType: .halfNote, sound: Sound(tone: .A)),
        Note(noteType: .quarterNote, sound: Sound(tone: .A)),
        Note(noteType: .quarterNote, sound: Sound(tone: .C, octave: 5)),
        Note(noteType: .halfNote, sound: Sound(tone: .D, octave: 5)),
        Note(noteType: .quarterNote, sound: Sound(tone: .D, octave: 5)),
        Note(noteType: .quarterNote, sound: Sound(tone: .A, octave: 5)),
        Note(noteType: .quarterNote, sound: Sound(tone: .G, octave: 5)),
        Note(noteType: .quarterNote, sound: Sound(tone: .F, octave: 5)),
        Note(noteType: .quarterNote, sound: Sound(tone: .F, octave: 5)),
        Note(noteType: .quarterNote, sound: Sound(tone: .D, octave: 5)),
        Note(noteType: .fullNote, sound: Sound(tone: .C, octave: 5)),
        
        Note(noteType: .quarterNote, sound: Sound(tone: .D, octave: 5)),
        Note(noteType: .quarterNote, sound: Sound(tone: .C, octave: 5)),
        Note(noteType: .quarterNote, sound: Sound(tone: .C, octave: 5)),
        Note(noteType: .quarterNote, sound: Sound(tone: .A)),
        Note(noteType: .halfNote, sound: Sound(tone: .G)),
        Note(noteType: .quarterNote, sound: Sound(tone: .D)),
        Note(noteType: .quarterNote, sound: Sound(tone: .F)),
        Note(noteType: .halfNote, sound: Sound(tone: .G)),
        Note(noteType: .quarterNote, sound: Sound(tone: .G)),
        Note(noteType: .quarterNote, sound: Sound(tone: .A)),
        Note(noteType: .halfNote, sound: Sound(tone: .G)),
        
        Note(noteType: .quarterNote, sound: Sound(tone: .F)),
        Note(noteType: .quarterNote, sound: Sound(tone: .G)),
        Note(noteType: .halfNote, sound: Sound(tone: .A)),
        Note(noteType: .quarterNote, sound: Sound(tone: .A)),
        Note(noteType: .quarterNote, sound: Sound(tone: .C, octave: 5)),
        Note(noteType: .halfNote, sound: Sound(tone: .D, octave: 5)),
        Note(noteType: .quarterNote, sound: Sound(tone: .D, octave: 5)),
        Note(noteType: .quarterNote, sound: Sound(tone: .A, octave: 5)),
        Note(noteType: .quarterNote, sound: Sound(tone: .G, octave: 5)),
        Note(noteType: .quarterNote, sound: Sound(tone: .F, octave: 5)),
        Note(noteType: .quarterNote, sound: Sound(tone: .F, octave: 5)),
        Note(noteType: .quarterNote, sound: Sound(tone: .G, octave: 5)),
        Note(noteType: .fullNote, sound: Sound(tone: .F, octave: 5)),
        
        Note(noteType: .halfNote, sound: Sound(tone: .C, octave: 5)),
        Note(noteType: .quarterNote, sound: Sound(tone: .C, octave: 5)),
        Note(noteType: .quarterNote, sound: Sound(tone: .A)),
        Note(noteType: .quarterNote, sound: Sound(tone: .E, octave: 5)),
        Note(noteType: .quarterNote, sound: Sound(tone: .F, octave: 5)),
        Note(noteType: .quarterNote, sound: Sound(tone: .F)),
        Note(noteType: .quarterNote, sound: Sound(tone: .G)),
        Note(noteType: .fullNote, sound: Sound(tone: .A)),
        Note(noteType: .fullNote, sound: Sound(tone: .G)),
        Note(noteType: .fullNote, sound: Sound(tone: .F))
    ]
    
    static let alanwalker: [Note] = [
        Note(noteType: .halfNote, sound: Sound(tone: .G)),
        Note(noteType: .halfNote, sound: Sound(tone: .G)),
        Note(noteType: .halfNote, sound: Sound(tone: .G)),
        Note(noteType: .halfNote, sound: Sound(tone: .B)),
        Note(noteType: .halfNote, sound: Sound(tone: .E, octave: 5)),
        Note(noteType: .halfNote, sound: Sound(tone: .E, octave: 5)),
        Note(noteType: .halfNote, sound: Sound(tone: .E, octave: 5)),
        Note(noteType: .halfNote, sound: Sound(tone: .D, octave: 5)),
        Note(noteType: .halfNote, sound: Sound(tone: .B)),
        Note(noteType: .halfNote, sound: Sound(tone: .B)),
        Note(noteType: .halfNote, sound: Sound(tone: .B)),
        Note(noteType: .halfNote, sound: Sound(tone: .B)),
        Note(noteType: .halfNote, sound: Sound(tone: .F, accidental: .sharp)),
        Note(noteType: .halfNote, sound: Sound(tone: .F, accidental: .sharp)),
        Note(noteType: .halfNote, sound: Sound(tone: .F, accidental: .sharp)),
        Note(noteType: .halfNote, sound: Sound(tone: .E)),
        Note(noteType: .quarterRest, sound: Sound(tone: .F)),
        Note(noteType: .quarterNote, sound: Sound(tone: .G)),
        Note(noteType: .quarterNote, sound: Sound(tone: .G)),
        Note(noteType: .quarterNote, sound: Sound(tone: .E)),
        Note(noteType: .quarterNote, sound: Sound(tone: .G)),
        Note(noteType: .quarterNote, sound: Sound(tone: .E)),
        Note(noteType: .quarterNote, sound: Sound(tone: .G)),
        Note(noteType: .quarterNote, sound: Sound(tone: .A)),
        Note(noteType: .halfNote, sound: Sound(tone: .B)),
        Note(noteType: .quarterNote, sound: Sound(tone: .G)),
        Note(noteType: .quarterNote, sound: Sound(tone: .G)),
        Note(noteType: .quarterNote, sound: Sound(tone: .D)),
        Note(noteType: .halfNote, sound: Sound(tone: .B)),
        Note(noteType: .quarterRest, sound: Sound(tone: .F)),
        Note(noteType: .fullRest, sound: Sound(tone: .F)),
        Note(noteType: .quarterRest, sound: Sound(tone: .F)),
        Note(noteType: .quarterNote, sound: Sound(tone: .G)),
        Note(noteType: .quarterNote, sound: Sound(tone: .G)),
        Note(noteType: .quarterNote, sound: Sound(tone: .G)),
        Note(noteType: .halfNote, sound: Sound(tone: .F, accidental: .sharp)),
        Note(noteType: .quarterRest, sound: Sound(tone: .F)),
        Note(noteType: .quarterNote, sound: Sound(tone: .F, accidental: .sharp)),
        Note(noteType: .quarterNote, sound: Sound(tone: .F, accidental: .sharp)),
        Note(noteType: .quarterNote, sound: Sound(tone: .E, accidental: .sharp)),
        Note(noteType: .halfNote, sound: Sound(tone: .G)),
        Note(noteType: .quarterRest, sound: Sound(tone: .F)),
        Note(noteType: .quarterNote, sound: Sound(tone: .G)),
        Note(noteType: .quarterNote, sound: Sound(tone: .G)),
        Note(noteType: .quarterNote, sound: Sound(tone: .E)),
        Note(noteType: .quarterNote, sound: Sound(tone: .G)),
        Note(noteType: .quarterNote, sound: Sound(tone: .E)),
        Note(noteType: .quarterNote, sound: Sound(tone: .G)),
        Note(noteType: .quarterNote, sound: Sound(tone: .A)),
        Note(noteType: .halfNote, sound: Sound(tone: .B)),
        Note(noteType: .quarterRest, sound: Sound(tone: .F)),
        Note(noteType: .quarterNote, sound: Sound(tone: .G)),
        Note(noteType: .quarterNote, sound: Sound(tone: .D, accidental: .sharp)),
        Note(noteType: .halfNote, sound: Sound(tone: .B)),
        Note(noteType: .quarterRest, sound: Sound(tone: .F)),
        Note(noteType: .fullRest, sound: Sound(tone: .F)),
        Note(noteType: .quarterRest, sound: Sound(tone: .F)),
        Note(noteType: .quarterNote, sound: Sound(tone: .G)),
        Note(noteType: .quarterNote, sound: Sound(tone: .G)),
        Note(noteType: .fullNote, sound: Sound(tone: .A)),
        Note(noteType: .halfRest, sound: Sound(tone: .F)),
        
        Note(noteType: .fullNote, sound: Sound(tone: .A)),
        Note(noteType: .fullNote, sound: Sound(tone: .A)),
    ]
    
}
